### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount" : 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount" : 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "7568c3e331de45eaadab17cf241eb236",
  "accountNumber": "1000000002",
  "amount" : 20000
}

### query transaction
GET http://localhost:8080/transaction/495117dd7ca74a0489adb2f9a23a01cf